import { Template } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'regular',
    name: 'Regular',
    description: 'Beautiful purple gradient glass effect with enhanced glass morphism',
    backgroundColor: '#1a0033',
    textColor: '#FFFFFF',
    accentColor: '#e879f9',
    fontFamily: 'Inter, Poppins, sans-serif',
    fontSize: {
      title: '2.5rem',
      content: '1.25rem',
    },
    fontWeight: {
      title: '700',
      content: '700',
    },
    padding: '0',
    borderRadius: '0',
    shadow: 'none',
    gradient: {
      from: '#1a0033',
      to: '#6b46c1',
      direction: 'to bottom right',
    },
    headerCard: {
      enabled: false,
      backgroundColor: 'rgba(139, 92, 246, 0.15)',
      textColor: '#FFFFFF',
      name: 'Your Name',
      title: 'Your Title',
      linkedinIcon: true,
      position: 'top-left',
      padding: '1rem',
      borderRadius: '1rem',
      fontSize: '0.875rem',
      fontWeight: '600',
      shadow: '0 8px 32px 0 rgba(139, 92, 246, 0.37)',
      border: '1px solid rgba(255, 255, 255, 0.18)',
      backdropFilter: 'blur(20px)',
    },
    textAlign: 'center',
    lineHeight: '1.6',
    letterSpacing: '0.025em',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and simple design with subtle elegance',
    backgroundColor: '#ffffff',
    textColor: '#1e293b',
    accentColor: '#3b82f6',
    fontFamily: 'Inter, Poppins, sans-serif',
    fontSize: {
      title: '2.5rem',
      content: '1.25rem',
    },
    fontWeight: {
      title: '700',
      content: '700',
    },
    padding: '2.5rem',
    borderRadius: '0.75rem',
    shadow: '0 10px 25px -3px rgba(59, 130, 246, 0.15)',
    border: {
      width: '2px',
      color: '#3b82f6',
      style: 'solid',
    },
    headerCard: {
      enabled: false,
      backgroundColor: '#3b82f6',
      textColor: '#FFFFFF',
      name: 'Your Name',
      title: 'Your Title',
      linkedinIcon: true,
      position: 'top-left',
      padding: '1rem',
      borderRadius: '0.5rem',
      fontSize: '0.875rem',
      fontWeight: '600',
      shadow: '0 4px 6px -1px rgba(59, 130, 246, 0.3)',
    },
    textAlign: 'center',
    lineHeight: '1.6',
    letterSpacing: '0.025em',
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'High-contrast design with strong visual impact',
    backgroundColor: '#1e1b4b',
    textColor: '#ffffff',
    accentColor: '#fbbf24',
    fontFamily: 'Inter, Poppins, sans-serif',
    fontSize: {
      title: '2.5rem',
      content: '1.25rem',
    },
    fontWeight: {
      title: '700',
      content: '700',
    },
    padding: '3.5rem',
    borderRadius: '1rem',
    shadow: '0 20px 25px -5px rgba(251, 191, 36, 0.3)',
    border: {
      width: '3px',
      color: '#fbbf24',
      style: 'solid',
    },
    headerCard: {
      enabled: false,
      backgroundColor: '#fbbf24',
      textColor: '#1e1b4b',
      name: 'Your Name',
      title: 'Your Title',
      linkedinIcon: true,
      position: 'top-left',
      padding: '1rem',
      borderRadius: '0.5rem',
      fontSize: '0.875rem',
      fontWeight: '600',
      shadow: '0 4px 6px -1px rgba(251, 191, 36, 0.3)',
    },
    textAlign: 'center',
    lineHeight: '1.6',
    letterSpacing: '0.025em',
  },
];

export const DEFAULT_TEMPLATE = TEMPLATES[0];

export const TEMPLATE_PREVIEW_STYLES = {
  'regular': {
    background: 'linear-gradient(135deg, #1a0033 0%, #6b46c1 100%)',
    color: '#ffffff',
  },
  'minimal': {
    background: '#ffffff',
    color: '#1e293b',
    border: '2px solid #3b82f6',
  },
  'bold': {
    background: '#1e1b4b',
    color: '#ffffff',
    border: '3px solid #fbbf24',
  },
} as const;